name: Commom
main: org.hqpots.core.Core
version: 1.0
author: HQPots Development
commands:
  chest:
    aliases: [c]
  invsee:
  list:
    aliases: [who]
  pin:
  setpin:
  removepin:
  copyinv:
    aliases: [cpi]
  mutechat:
  spawner:
  ipreset:
  cc:
  rename:
  staffmode:
    aliases: [h, mod]
  freeze:
    aliases: [halt]
  vanish:
    aliases: [v]
  blacklist:
  autorestart:
  creative:
  nightvision:
    aliases: [nv, bright]
  staffchat:
    aliases: [sc, ac, adminchat]
  report: